# Generated by Django 4.2.11 on 2024-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterevent',
            name='event_type',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Tornado', 'Tornado'), ('Wildfire', 'Wildfire'), ('Hurricane', 'Hurricane'), ('Volcano', 'Volcano'), ('Other', 'Other')], max_length=50),
        ),
    ]
